version: 2

sources:
  - name: staging
    database: 
    schema: de_zoomcamp_car_sales

    tables:
      - name: car_sales

models:
  - name: stg_car_sales
    description: A model for used car sales

    columns:
      - name: year
        description: The manufacturing year of the vehicle.
      - name: make
        description: The brand or manufacturer of the vehicle.
      - name: model
        description: The specific model of the vehicle.
      - name: trim
        description: Additional designation for the vehicle model.
      - name: body
        description: The body type of the vehicle (e.g., SUV, Sedan).
      - name: transmission
        description: The type of transmission in the vehicle (e.g., automatic).
      - name: vin
        description: Vehicle Identification Number, a unique code for each vehicle.
      - name: state
        description: The state where the vehicle is registered.
      - name: condition
        description: Condition of the vehicle, possibly rated on a scale.
      - name: odometer
        description: The mileage or distance traveled by the vehicle.
      - name: color
        description: Exterior color of the vehicle.
      - name: interior
        description: The brand or manufacturer of the vehicle.
      - name: seller
        description: The entity selling the vehicle.
      - name: mmr
        description: Manheim Market Report, possibly indicating the estimated market value of the vehicle.
      - name: sellingprice
        description: The price at which the vehicle was sold.
      - name: saledate
        description: The date and time when the vehicle was sold.